# Generated by Django 2.2.6 on 2019-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('catagory', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
    ]
